# Generated by Django 5.1.4 on 2025-01-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAcessJWT', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=80),
        ),
    ]
