# Generated by Django 5.1.4 on 2025-01-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAcessJWT', '0003_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='user', max_length=10),
        ),
    ]
