# Generated by Django 5.1.4 on 2025-01-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockProducts', '0004_alter_stockhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
