# Generated by Django 5.1.4 on 2025-01-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockProducts', '0007_alter_stockhistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='action',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
