# Generated by Django 5.1.4 on 2025-01-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesRecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='refound',
            field=models.BooleanField(default=False),
        ),
    ]
