# Generated by Django 5.1.4 on 2025-01-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesRecord', '0002_sale_refound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='refound',
            new_name='refund',
        ),
    ]
